---
- name: Create Container from webimage
  become: yes
  hosts: servers

  tasks: 
   - name: web container
     docker_container:
       name: webimage
       image: webimage
       state: present
       ports:
        - "8080:80"
       tty: true
       detach: true

...
