---

- name: Create Web Image from base CentOS image
  become: yes
  hosts: servers
 
  tasks:
   - name: Build image
     docker_image:
       name: webimage
       build: 
         path: /etc/docker
         source: build
       state: present

...
